:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2018.1
:: Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado/2018.1/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7a35tcpg236-1 ../xilinx_com_hls_doImgProc_1_0.zip
